apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iEAfthwcdS4RN+HoCgA=,iv:Y0Bu3TwOtUbXmavqdcTcKIowRpcyV2b9DSKYWdtYTLY=,tag:wafZenT7ac5UeirNbJs4Hg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:AyXg4X9DFP8dWTC1/Jh7CwURKeKiyBfwVAfDpd+6G/V18KqWuQ==,iv:yDVuLbREJ0teG3fZ2KgdLQpDtcFEtIPUg39QKxBjIjo=,tag:zWExXoI0EAc5uga9dS7GNA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:NT00QaVrIESutI5TjwdLiw==,iv:6bzf7FTI3eKguNk8Icf24FRB4EsIgn0peCkpB0gkSJk=,tag:3Bgg3PwRFj2LhuZTR5gH8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVG51c3dxWG52YldOdTFn
            UWhDM1JVcTgrb1g2ZHJzYmljTU0weHJsS3c4Cjd2K0FrT1pGUkJTM0lUejFNZlht
            YWNsa09zb21vWVBKZDFzMEV6QmhIYWMKLS0tIDFRVTRBb21meXdJV2pQT3NsS2ti
            RzhRTGRjMTNSZjQrQkhXY1dOb2VzYUEKp2Rz6DXAiNf/4kARnMOF2gDUh+v88QCm
            PD7Viwr4h3cY0VmkT/ELrtd/RyOZmyeMybRP0umriVeGEIoPO9vd6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:L4E9eYJuGsnIG+7loHfhMWT+rzGcpOp0/g+pcsFUfgz7C35STDHv/H4SAXmpCHswsSG+4tQ1Px+qOM7Bh7utTy14l5p7LP+VuiVZAXPY+q4vt2CYmmubuxSOdIkTB9a95J9IBOsv7/lRNtskPBE4ebQRqhiItbAVeVTJNhPGhAs=,iv:A2kg8GNQLbeSLT9EZxWKB2nRj8cwvVqWoLKqKnl2LpY=,tag:DwtYMo0dNUiJiv8ymJptcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
