---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config
  namespace: default
spec:
  storageClassName: sabnzbd-config-pv
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  iscsi:
    targetPortal: 10.10.1.228
    iqn: iqn.2018-11.io.sdboyer.h:kube1
    lun: 4
    fsType: 'ext4'
    readOnly: false
