---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrules
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml=./resources/kube-state-metrics-config.yaml
#   - name: alertmanager-config-tpl
#     files:
#       - alertmanager.yaml=./resources/alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
