---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        MINIO_ROOT_USER: "{{ .admin }}"
        MINIO_ROOT_PASSWORD: "{{ .adminpw }}"
        MINIO_PROMETHUS_TOKEN: "{{ .promtoken }}"
        # Authentik
        # MINIO_IDENTITY_OPENID_CLIENT_ID: bTrern87mkr6TFjynOTOWw947m0ACThFvwGRMFe9
        # MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ .AUTHENTIK_MINIO_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: minio
    # - extract:
    #     key: authentik
