---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: config-hoperestored
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
