kind: ENC[AES256_GCM,data:ZQ4b+0hz,iv:7Ye7JsdwV8iYA5uPmhWQ9dExgMZfSzHLNL5iY6H1BgY=,tag:WB7zvDVqQeI2bcUUDJYjVQ==,type:str]
ansible_user: ENC[AES256_GCM,data:qIMAfw==,iv:nsm37bA7eYq5TsdsrHy2KCdCqwDN4D7gVYqSidKpEjE=,tag:sdGpkGXU4x72VpRUZPV8Ew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Wm4=,iv:LCPlN6mjuuqKCEHspqedv3Wrms3K+qyHd2zLRlelPeg=,tag:rCqD9Jhr8aXzfq5emyi4UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eENkUzZaWnZzb1BUTTg2
            R080a2FjVE1JV1hFTytTeVd3TFYrZW5ZNHpJCnhYdTdkT25nT0dST1U0Skp4TmFO
            em84c1RaODhBa0FuNFpHYlduWUN1RTgKLS0tIGhSZ0k4dG5vV0ExaGlDUkJzaWVo
            VzRNc1YxRnlvMXJNV2ZaT1QrdUozVDAKDX9J38UHDM18x1TZB9B11wsc2racmJUo
            m2WqHbeODvSQhgfSYSaXXn9BRP5OY3Y7zyqXAPJb3WxviEWwe69h3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:7r6VU5Nj8kugmqU6R1Meqr/gLpKfnND73GAKzge8IeTOQCikZjo2/5cKO9tlF+hx5PDzpR49NJhx8IGmMOarsrmpbMT7yIv4taerwur2+zel7mS83yhTmYQUs6UAC0x+3sSeh+t877e/1AGRKuZeqCix7K+kS+JXk1tXx2eD/nI=,iv:MRiqRxneUMNmVjAXyYk0dMNV0Df/2QFnZUtoDZl935U=,tag:LEcTy+vb5sSr64UIBtkh4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
