kind: ENC[AES256_GCM,data:hRfYo5WG,iv:I6aP1DnvWpvA/7yZ2QmrQvlOm6E1VoeMCMw6EFTRV90=,tag:FJS3F9XLtOrhyx3OlsmYOQ==,type:str]
ansible_user: ENC[AES256_GCM,data:hAxhpQ==,iv:Aj3tdP5gUVEJoVR5SNYAXj05ZdzuE24TJZQRLglN5Gg=,tag:rhFVak14/+0Oxwb2D03l/Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ejE=,iv:I/Xp0T/c7jJfiYbWmEC4RW7y7EP5MpCuIYNCIitddeU=,tag:rsuUq1H8/DshYgiTN0UI+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ1FQL2VoUUhrSTQ1MW4y
            d1ZnMDRQS2tFYTBNUElzYmIxaGU3bjBTUzFBCjdONkZmekthU3REVXZ1Y08wY0p4
            dVVVNG9EaC9FQnc2L0ZpbGp5aVBiRlEKLS0tIFdsVFhzN0ZyeXl4SFhQOVdsVUZy
            cWtNcGVwLzEyUjRiVlpvbk5NOXE0M1kKcLZxKpTm+2vuwCdW0pxF/fXmuDTNLrFK
            MQ22dn/Bkh/ARDekMnKQpODa1kmb4kLI/pVRUu4xQVGZ1f4FxNdflg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:5Vn05NMH0GddeETX5qpvHPvPJEZCjtZ6boihlSIVIY+IE0HjbRqBGsf6Q4dTZdn8tDiwtRxbF0O6rYBed2hgbOf+eX25JXvJQs3Or/b0CUDOr/uvHvDElT5BS70JYR90rfK6jNXev86DmRAkk3m1Mudkrs9fsm6M679XwKjwrDc=,iv:xW4z9X1mmTO0FVnEl+xLGTGahdfFdUYgSSoezQB7Q+w=,tag:O+Ti9uROrUerXiq8vt1MDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
