kind: ENC[AES256_GCM,data:eZOmjj2p,iv:0e2wA6GNb9Yp8zGOZoO3J+HJHZfSfkUm188+hl9x1jM=,tag:/YGRNNPRiAWKyM9oizd/+A==,type:str]
ansible_user: ENC[AES256_GCM,data:2AFArg==,iv:qjwhjiKr8xBZIlQ9biYFyZHYewl9mH9mCDIvzHSpL9E=,tag:VcHYprHmZgCQjvXV7TtEVQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GUo=,iv:qprkU5kyDtOM5GpoYbA6ovxL6gPBivARMU3376TEQCA=,tag:aXaft0D4BqRI2sVPSwe7Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdWc0RXc1ZGhIUmplNXdq
            SVFXT3dvaVVVcFFHMzZUYU9Vbk5PWFp4eHpNCno0YnZxQnN5MDMvOERxdXg4MHRV
            d2FhSmpJdC85OFFJYi84aGplV0twRjQKLS0tIENPazBPcXJXdTJ4UkVTcWNMSWdw
            ay82cVl6U0gzU3V3S091Y0t2UnFxYTQKyDOw1NLO7QDp1NRAN1J080CLQzrZgv/L
            59inCYS1zZI8nhpd1J8RpNjY8EV1jWti15pcJLhKSPKSfHcB4wF4PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:HVOHmN4CTZ8Ts9Ijqr3JFAz/t48Ii4cWdzKL98IQAPL5/8jKND2J+cdHmvrZvR4HwOw5vtAofl0wnxlEH2b2M/mHw5pOWm6Ii6B6seCDZ9xEkd5srfMEgGzNOaTrlJrMpUDF5mXbjgE7nC4CJrXPIEZaQ9cGanVQ3ZgJ4Yabtgs=,iv:brz671p2F2c3CjwY5EdTdVaBtOyFUmf/rwDUxj7GVgE=,tag:aF4KudJ++4myIl6R6924ig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
