kind: ENC[AES256_GCM,data:uwLCDB8j,iv:zwpYe4mbUL99MHhrQRFFaPivdpdECrY50f2nhELEAAI=,tag:InylgoiSKkkAH01eRMTElQ==,type:str]
ansible_user: ENC[AES256_GCM,data:29FEYw==,iv:bLLFzmJDyPPtpnMlXe0CY+cPQFQj/ffWte612KNdVaQ=,tag:JXWAHY4vl5kxokzph/67iA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:EvI=,iv:3cSqVNOaPnsIprMQjnuD+h7xSZLNCVXsnN4YCUnH5zg=,tag:DomKZpvwT4XEe9+NfrZCwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNXc1ODE5YWhzU3NLU3NG
            em44anl1WlB6UEg0THdjTElsV1RaaklTMVZZCmVPWGV4VkJwai93VU1ndGc5U3BH
            aWhPWmptd0lPcS8ya0pOaWV5QXZoSjQKLS0tIEk5SEF4MVNUS05GZjk0ZkNZOUJS
            cndQdEttR0x0T09ZZ29Pd0hWVm04YjQK/EgMb+I1zKLDGQVYL38PJoC3Ky9VgWkY
            GtkZ5gsEiAT7vryUi/01518RnYnD7OXxxjr93o3ZDuZxKKuOGJNmCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:N3TPBB1PCNaLkzdukr5TkrzvpOKy5HLKw3YvDm9UkPFWRqLhrAtpZvTElMmmZS9NuA2OTsbYf+yygXSyC8AHAzZJoQEMcxPJuYEPeFIyFOYupUq8JKEPsFJn/iQqiO4HRk9ybaCNQUfXhW0lRidgwj9yByhxKMRb9OKP1QooSyc=,iv:Y2CqpoHeYSwnzdmywT8O3vzdWqVsn/lWWBFQZS9V85I=,tag:rqQ2895VNxKlEOVpqf4aYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
