kind: ENC[AES256_GCM,data:9VCCi+mu,iv:rVQTBOaoNxB9lADByXDGccxOMMBkzvXOhLcHLDRI+NY=,tag:gL3kn5QhN4R1qfszkOrLyA==,type:str]
ansible_user: ENC[AES256_GCM,data:pUpSzw==,iv:9Z6tJtuuI8a8BeJuXPpNIxVJngrhR/tf2JUkz4YwLvs=,tag:vSwMyKdhi4KRoejeEZM2yA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1cs=,iv:JQN8ynDSjvfo+LHoyvGbvU12z7r7jx5/w0wWOmQaRXs=,tag:7GpjGPfTPkixSY6v4wJsgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRlp6akRSa1ZOWHlvNDhj
            aUtybk9KRkxpV2NMNDRGcytlYTUvMk5RZ1RFClBMbDhyQnpNM3h5SFFibVkxNDlZ
            OW10dzlCdy92NThDM3dBd2JIdkd5Sk0KLS0tIGg2V0l4RGFlQWJkZ0UyZ1JqYTdX
            Y0J4Wm52Z2FoYUtUZW1CWEJUeTZzOTAK5lQqWlLcBlO7bu5BrVamDNK9VzfGCXXb
            BVXTgmCnjxROPHuZ8bm2J+aLDG30C/lSFnB6fg9aD3VAq1FH244LFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:O2oDE5Fmvi3prtpeg+2vzlHubKDiYu7bvnYVlnkki/99ohXunxegXoLlR6uvs1xE+eURx5VVD3r1HniqWwJXPS+dXRBaX5KHGn5wvHdmMZHbmosyDmkm8ImpJNl9wRYpbYTTWjhN6u+fTzhv1E9y3EAAitRq7FpHPtP2d39I03E=,iv:RKf/TifvQBbS31pnKBgnOGnaIr4RsPx7TaayaAAr8mo=,tag:05lklhiKzRrbWUv4dJca5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
