kind: ENC[AES256_GCM,data:t6exv+Sp,iv:6+Ps3Gn7v3binWXtBeC7k5Q1IfqBC2AoFoWVyKP67xU=,tag:naHR6zRUbIxpA0qHVLvieA==,type:str]
ansible_user: ENC[AES256_GCM,data:i/mNpg==,iv:UsFRHJ1M9mxuTy5T7i0E0tm5NGEYOzVAQL4+ZWT3+Ak=,tag:DyQHpN7BfUmz2FUa6cZJ+Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cbM=,iv:PY5Hv3Lx+2DMlj+rFgb3V2qYkCVf8Z8dxODubh8RmaU=,tag:3hnIi1tW0RX9nDTrncW0Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUxOWjRQU05NQ2x5NGls
            OHJiUXI0aWI1d0lDNjRNUlB3bzJNSGZOdVVvCi8xMTRHeEFKMENPYTZVNTV1eElZ
            RzVlRUtoZHdCcFFha1pQNVZHN2hja0kKLS0tIEJ3YlBpYWlxZjU2dC9RZk0wck5m
            Uko1alprTGVHeWM0ZkpMMDZIcjZ1ckUKh3QJNHpteVKVfbCIQY6SjOkrZOxGvJVX
            IroZSMViT/IyCyjy90bLa9MAgzVed0ATjWIaYph/18674UV2o1UoNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:iegU6u0UOjsLa7MeFkQW3so0mEimfhMBPmQdQ8yejSVYLifxmTRnGBmTo9O1WAnW8v62n3/izY17PC7a+tG8IojmJ0NeICgqJHzZ18AxWq+oWv2XKOFh5psZ2RpKlFj1wkDfwSmhfXbe4bk72Z8OIDNSXJ5OBsqCHezBAt6STvw=,iv:i6IS0OKzIr8EjFM19WH5AN+xjxTdfQ3fEy+FMDh5Pvc=,tag:nkhnKul4C6hoxLlz/0qW8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
