kind: ENC[AES256_GCM,data:8w/EDvP/,iv:DK2taYqpH0BFdb2PxCECUxmeEorgasIOMoPGD3qcjX0=,tag:jevDr6/eUnn0RvojOKavEw==,type:str]
ansible_user: ENC[AES256_GCM,data:0FDn0w==,iv:f8XmSzwHu/6qPThv3ui/sL6tYHhcNNpbFMIQdKkEDJI=,tag:CFnYJrmwBf0qWmPYMmqupw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wLA=,iv:VsR6kXGLqW4eudT9veeYcZDtq7Srxd2/eqMr18baWSg=,tag:+6UlissCY2/BEVlrbsoiUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVlI4dndOT09jV3JTSkxJ
            Z2lpam95cFhRKzJtVHpsZUptV0ZyaTNSTlZJClZpRk1iZW9vQ0t1alZLdzg5YklO
            MFdJUlJmdHNtdGtIZmU3anBYa29NNFUKLS0tIFREemFZTE15eWtMdnpNSjJqUGNR
            OXAvTWRVdGQ2UC90VmFDdnMyMVBXUDgKZytMK2Z01MFSCnHgpplZ0FIb/4vKvAN5
            9viMcxoJ/LlphWMia2w4/dT5Z6DCXzq/1VXOqWcJCBWLfLes+mfgXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:zO4ZizBzhCUaQl1vi1gth5dc1HGBuAsBfKXif2OlbaJqE/3R9KgCrWQpYHCiCkOcpguhvGFV36jawLd+oLtcK+uGY+y036vKK/p2rGH/s93qp54CuV9bPwGvFUvFBigOCH2Nc8707cdC/GAdZOvfvtqpjrbKHYtwfooTBw3j15g=,iv:sjBDfqtQSN/fsJjxKxukz1uw5ZIjwKfjsYgrbYBr0Zg=,tag:uWsrAcR8jiSNRZvbzgNH0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
