---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 13.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: redis
      namespace: database
  #   - targetPath: objstoreConfig.config.region
  #     kind: ConfigMap
  #     name: thanos-bucket-v2
  #     valuesKey: BUCKET_REGION
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.34.1
    objstoreConfig:
      type: s3
      config:
        insecure: true
        access_key: "${AWS_ACCESS_KEY_ID}"
        secret_key: "${AWS_SECRET_ACCESS_KEY}"
        endpoint: "${AWS_S3_ENDPOINT}"
        bucket: thanos
    receive:
      enabled: false
      networkPolicy:
        enabled: false
    queryFrontend:
      enabled: true
      replicaCount: 2
      config: &config |-
        type: REDIS
        config:
          addr: >-
            redis-node-0.redis-headless.database.svc.cluster.local:26379,
            redis-node-1.redis-headless.database.svc.cluster.local:26379,
            redis-node-2.redis-headless.database.svc.cluster.local:26379
          db: 13
          master_name: redis-master
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
      networkPolicy:
        enabled: false
    query:
      enabled: true
      replicaCount: 2
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: observability
      # TODO
      # stores: ["thanos.h.sdboyer.io:10901"]
      stores: ["thanos.boyers.club:10901"]
      networkPolicy:
        enabled: false
    bucketweb:
      enabled: true
      replicaCount: 2
      networkPolicy:
        enabled: false
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 60d
      persistence:
        enabled: true
        storageClass: "${CLUSTER_STORAGE_BLOCK}"
        size: 10Gi
      networkPolicy:
        enabled: false
    storegateway:
      enabled: true
      replicaCount: 2
      config: *config
      persistence:
        enabled: true
        storageClass: "${CLUSTER_STORAGE_BLOCK}"
        size: 10Gi
      networkPolicy:
        enabled: false
    ruler:
      enabled: true
      replicaCount: 2
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager-operated.observability.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: "${CLUSTER_STORAGE_BLOCK}"
        size: 10Gi
      networkPolicy:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
