apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lK99zkPbNBj8F7ib,iv:vkZ3NYugR8qkAcNSpEuKA3Dyxjpeybvn421c1UKZF/k=,tag:46tRDiyjKNp2k5mLq70kfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeEQ5cjM0NFE2Y3hRWXJG
            emNWN25xZGJBVVBtaVFYNGZ1T2xPZ1dnaDF3CnBKS2VGaGgrbkU5Qmw1aVQwdlBS
            T3BNTHlpQ0EzamRSeGRUaU9HVnJpTlkKLS0tIDVVazlXaG5MWmRkSEcwbkFIMTdG
            eXl0a293L0poTmdia3VvbGpRQmY2azAKPk+3AAYxX9vXCyJIBBrh31sI2oDECuSk
            5DciwpUKV6al637JHtQV06AhJA+TXhdST6n8edQbkDA5VqajpDetnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:WUR5wqrX/62Kqt8QFQC/GCjFpnwqEXGoR1aI7HzMlx4pY+I8CFh9xr3iEg5gm0B2pwSnzO91yGBLecuYcy07AYekUKwXRm+xRtjBOb0mmSxAEec3R+jD7dsciN4V1JlAJl0BBc8K8ldJwkmrr4JePoBRmDHzBerIB5gRlLI7Jzw=,iv:OEUpRlVKGYoxPtFWulw9HAmz7t5kp+Dku9RM2yGzlkY=,tag:Oyl+lsQ/4g8HxvxjS9C/vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
