apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7AQTF4vgnSw9rAWg,iv:1ijgJkQGZlbfl7yRufgCTxsjmRjZ3GsC5XgqDEYu5Oc=,tag:7FBSRiofm7Lopkjc3dywtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEejh0K3d0dmoxV0EvTFhh
            TEdleVk1emQydTZPVzNkMkFacWk3SC9EcFE4CjVYVGhmTmM5OU9qRUk5bTVORUNH
            SWVmZk1wdmxLMFZBQ2x6eWUxSUhZRUEKLS0tIGF1NW9CQkVpOUFaaURoajhudGdR
            TUdGL1RJM3RueTJNSXZxbk9YZ0pDa1EKLbvlIG2wlvsGfQOj7q6sjRXu82SP0ffz
            5FBQv/LhO+0VxokCtZbT6LWof6j7eORO/OBKZ3k7Fu2z7f5QgGJ2Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:nSmH7BiIFG5QK0TMdwu57ci1Ka7b5blJHmk1uAuG50MzUOdOPQOLJVDPCeBZpdtDfiEGg0QmNNcqu4cdLfAPzcsZTT0caQhBHeJIaB+Vi25LS8NBYrKTIMH1io3QJLfo9pMDa/GDIC1ONWw64YGn3Yc1jthtK4Z2grTZ/iG8QM4=,iv:v3NKJ47DMu71QthdGdAzrOKJz4rbA3iboPLDtyfJeF4=,tag:655sVRVxu+Y2keSjsmw9gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
