---
kubernetes:
  children:
    master:
      hosts:
        rpi2.h.sdboyer.io:
          ansible_host: 10.10.1.239
        rpi3.h.sdboyer.io:
          ansible_host: 10.10.1.153
        rpi4.h.sdboyer.io:
          ansible_host: 10.10.1.138
    worker:
      hosts:
        rpi5.h.sdboyer.io:
          ansible_host: 10.10.1.237
        rpi6.h.sdboyer.io:
          ansible_host: 10.10.1.215
