---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi-freenas-iscsi
  namespace: flux-system
spec:
  targetNamespace: democratic-csi
  path: ./kubernetes/apps/democratic-csi/democratic-csi/freenas-iscsi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
