---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
  namespace: home
spec:
  storageClassName: radarr-config-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  iscsi:
    targetPortal: 10.10.1.228
    iqn: iqn.2018-11.io.sdboyer.h:kube1
    lun: 2
    fsType: 'ext4'
    readOnly: false
