---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sabnzbd-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  dependsOn:
    - name: cluster-apps-sabnzbd
    - name: external-secrets-bitwarden-secrets-manager
  path: ./kubernetes/apps/observability/exporters/sabnzbd-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
