apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ggPubVVzXmsPEZhe2KpnR7o0oSA/JVnG+R1f32tdWT95E1agTVnL7w==,iv:tvKPqhmdUXLSh6dl6WuqaLIyLorvlNJZpIpsPKdpLQ0=,tag:kGZYKN2plqVo3uwQQGjkGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age152jlmwv75v9htehsuprmwd3nmfr4kzqd6lpjgnk8juunpps6349spxehnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcUtzeFVkN3RnVFhkQ3BD
            ckl4ZEd4cHFoWm9SUnh6RTFFa2hjMW9kR1Y0CnRFRS83L0ZxY05xT0JPK1dFUUpL
            bmpNOXcxUVoyMXh2UTAwMEJVejdyUWcKLS0tICtMeHV2RlZRY1hWSVN5S0FFbW1t
            TCtqNFRBTXZjZk1tY1g5ek1TUVk4aHcKTMLuP4RIQhQm8kLJmSuABp1HmTduAVRl
            fO2yhVoz8HB8W9dnUExHtB65zKRmVWq9vtr+DmkQy9VNWxFAtvGNBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T17:01:42Z"
    mac: ENC[AES256_GCM,data:vyX0M/vENru84QlNayKuL7i7LN/U+Q6Ows6OqdhYR6M8wNa+iGvLOq71PHHxfN5QswzDQFr6DW3TWtk/xjxgcQoOGzmJ0qizVn5UWqNYhXS+328vVX8XVmnl7oQF3S4IA9nB49Q0l+D1UPFmL/9+XShFJsYHSFds8ZLZ7vcQWzI=,iv:1KNzwH117CxPlXtIUxxzGY1PS1JJjI5GY52sUyRqVl0=,tag:rd+yh1PmoGtmMEOtHDYbGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
