apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:4z9z6CmODK1GzImn6HEqzVhnjkrg51fo01RMAycCYTogDDoAnzabFg==,iv:AATSa1PoYHKpKzHDCnNWY9IA28yc9TSIYce1ScbrG98=,tag:ca7TLk4k+QAKMDysEB7VAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age152jlmwv75v9htehsuprmwd3nmfr4kzqd6lpjgnk8juunpps6349spxehnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaURiSmFIZi9ZeHdPc0Jt
            L3kyNDJrcWJGZWdkL1JSOXA5b1lYOTRUd0ZjCk9lSWsxcXZOK2dBSjc5amZTaGhk
            b21QS0RtM1k0UDNtbHdLTmN1RkNUcmcKLS0tIEpleEthaG9OUkVMN0NGVCtkNng3
            TWdidG9SZFpEbGdSbUw0SzQ3ZkIwV1kKrTLoU6RynHO3FAB9Ll6MEE/M9Q0FDGO0
            16EjqD7fxLhEigIcbByXQE0Gaqq9oO9o28+m5dLOqbIYIwIBPIpnsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-31T21:01:39Z"
    mac: ENC[AES256_GCM,data:WwqKwL2WFmLsmO9et4Ol7DF+EH/0mNRWHyzE7rArLpqPXNH6Wq9+TQzioupn0Ecm+2/9xwc2MtJ4QXvl1Xk4Xmf1XHD/Vpomu2A/E/CFpefwhfQaA9Y2+w4eSYRwbWw0BtCKFWHIewXs6YqAwnee7NHid95060tdx2KYPIrsT5I=,iv:ZJifGCjC027ykZVlQi4ufq9c8lBDrOeMAKW57zPhq7k=,tag:YcEBNhxzT0wFdjLdo48HXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
