apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ilQ6s2/LuqEQwrwjchRS/5IjN1QhnK4kFtnFcwNxwtA28ZpFW3h0ew==,iv:kg35jVWU1k+zSXVa0peMul68BhyZ918sIXiii/+RlL8=,tag:lMIiNjNzbntSWRTClj6w8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age152jlmwv75v9htehsuprmwd3nmfr4kzqd6lpjgnk8juunpps6349spxehnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VU14b1ovbktlL2tYUjdr
            Y2dBRDhIUmRJU0FUZ0dUR1AyV0NvQlEwQ25JCkIydm84M2tvR2JRWmRkVjZwV09h
            cWxHWENsSkFMaWpRTzkzVGtwcEFqTmsKLS0tIEJoVnZJa1NEemRxWEtDc1BqdzZY
            TnowcVRiL1g3bm1lVE5xRFdVRGxEdHMKa3kKFGiUV9yA2/KgGMGYn/ngoPSMfJEV
            EnLUlAdJ6Vh2sTCkg1Aq6kAl8BROb27yIC0ZePa0jvQNa76GPeBJKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-31T20:25:05Z"
    mac: ENC[AES256_GCM,data:RJnRwy2aG4lSeIQfOcpZ68MbG8hDxXrgXH30+0AbFe8dIDKY1X40DwfknrghPoUxZQYYENhICnf00zcqRNBh+fPcGWwP3nT71DCxt864jawBa4wuhCdKRch/bYLNqXC7V+UAlWOaRUEzlkm/NFlT/Uo3Woc4Q66nND33TpNOUyc=,iv:Ii12XiHZDUYnToeo1fTkJt1sV6wL1MeBocbSB4CdhKw=,tag:rcHdapUkijKYBHYElF081w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
