apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0D2X8K8+yoKb4Q7564JpLzZiha0iVR0adtScbSewUdXT027dLg==,iv:17f9Yjf1jOdqr6aMtdTGYY62lYoPLklblvV/NI/0VNY=,tag:bUIpTWKmzLVSRUBQsgLlVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S3gxcFEzK2lCSHJTMFhU
            Q292RUFJYWFoa3JtbHcyRm1iemE2aWlhMWpFCmJVZU9TUE1qWmhtVFo3bkI0SEg4
            ZGlxVUQyWFIwOTdtNzVaaUozc3dMK1kKLS0tIFF1T1RMZWk0bks3YkVrUm9nYm9k
            Y1JVbE0zT0tOeFNKZGEwazVaTHJKelEKsYKGnujHPH3OXfrLPedzEcbG7VE4M2cQ
            08Yj65KrCdw5B/6gLJeNiWqJbzWIc2B9N2O+4JEh2Uwumi+uEwsm4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:if2hUUS5VDUEodDuOjiz4Q7jvz0eR5oaF6dSAlYM9DDlDZv6x7umtrkNyfqYOl52sI/QfhgG7M7wxwcsx6ugOWTO2hjBOsX4AMM3swVpgzguVtJ8OYontNDKtOmSorGkkxPuX+pWEM6bw6bbMGxBRBYFmcMHKSh/5Gxuff8qb3g=,iv:B5L8OZkHpIAnRD5wE16ezEPvYDOD0hwx2i9Ko8QFrPM=,tag:G6/QQuXR/R/gwx7st5EsYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
