apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:5e8uaPne1hUhAzGqANw+muHEtqwwVJC6EOHuDAoqQfTPLaUn2w==,iv:914RrAmKyTABpvoToORG6BxB67XQx3pKM4kYE8HVB4k=,tag:9+3aEmtHVwGLCzbS1sfb2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRVVlTExiRW1rNGluQUsv
            U002a3JOZWZZL3JuZmFValptRTZUUTJubzIwCnRDQ0xLMGo1T1BZeFNPaGwrdTRH
            cE9xeGcxTWxmSGE0Wi9oN1JuWTI3ZWMKLS0tICtJTU9NVXJIMVhhY29BYks1MVdp
            MTgwWUJSUldBb2hCdmJKMG1tcllkQkUK4YltQbSJ3qhXekG3gYUmMMGw7F6GH/jt
            TOCfhL5CzqzsY1eG1rR2Zo7D0RYY77qPOdRKtXBjsK632fdPmC4hcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:ZdEoEXbPlNLd9UJrlKb/0DUEhoI0YsBrkNKo0LXJQy91kJn1oQVQ++nziY+aQVoYs85Or/Ogt/vwaWeJGx75FY629b2cUscoG5y4D2R64fWceUfqWRhiDi+8ABYx0/gVwU+LXVcYO8zeWfof/o5P/UbOgtS0D0JYbMOTZtHHToQ=,iv:W/owJu5EnPC5F34S7S6q5g1vRBtf5uuE5L9R4P9Lygs=,tag:S1/ql6uPNrDuxSJ7wmTLoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
