apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Z+yRdd1NoJlTraHvtL4=,iv:2I3u66SVt+XgwDGV7ydigyaHlmcgnLjP7fikM1LIIA0=,tag:M4hvFVJrMjNFBYf1/rh1yw==,type:str]
    api-key: ENC[AES256_GCM,data:I2CvbvJGbpLqcfI5yFTKXZIA4m6FpYg4YMDESqbNxrcsLotkWw==,iv:7ebmq7X76PXIt9hHkkJCiLvi8QZXvWZ7/DO0Z+27B5w=,tag:iZgRz8LWBtSaO6jEshiwaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y3M5MVNURGFrajJ4ZW9h
            enMxdGtZZjZ0Y3YrcWZ2NG9McnRleWszZDIwCjVOWGt0b0gyNnBLRkRWUDZSMWRo
            T0ZlL1BaZU9Db0VZM1hTWkx0Q2ZVUTQKLS0tIExQOUVyVmwxSjhRR2ZjKzFTa0dF
            NTZXQlArRVlIcngyOUQxY3NqRlpZRUkKt/yS39UzDQGqIY9H4Ipv78zQ8Q3Xs0Ik
            K20wUP+31mDHvuMb2vyU50LO/05svjxp2zddp7m/eJ75X6a6U8+nUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:J8lxGh9nAog/CzGykGfQW1m5DZyD1xPKMeEa/I7Nig7Uk3Zv1zc77mtQF4QY+G/FHDc+0aiN4hlULpNn9XCq4apzFCKctMs0S7C1qGRgA6eW28z4yJPPqvUDuafkUNjRZLO5P4CRsuQwyOpmoaM/zAR9uex57TPl0Mk54NSeOG8=,iv:T73fsJL/kptByw/FKWtC2PdEjQeaHv3dGM5McDDQylY=,tag:RlmJS13rYzXZqCnnaW1pKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
