apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:PJAHGHp7OgoSq5lDOao=,iv:uz98k7Z7mWRxOAchxX20kdA0ATJq1E0ixRDKypQTgig=,tag:5ma30F6ARsPsE54hOyFH9g==,type:str]
    api-key: ENC[AES256_GCM,data:LeeL9zL+/imNEqgdJC/w+p74ZFHgXzk/fK0ihR/tgjHLMGdk6w==,iv:X0JRr+YmN1ua7PvzGCrPPzJIiUNN/23ZPb3QrBWxRm8=,tag:g3/a7u9SCVj2CeCxRHsrTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL1p1WXRVSW9uMU4yTEhS
            eU5aU1A4YkZjeXRBdmNnNUROVDJ3OHpiOURnClhjdUxiSDArSHVoK0J3VzZxVU9G
            VWNVSXZjZE5aQzVEU2xZQUpOZGVtalkKLS0tIE1mSU1IRkZqOVRZTVc4RmJOYmtP
            RGpCZ1VFY21qa2xRYXM4UDdTMmVEbDgKtCCoaiJHucK3tHJVUeHA9TdZWwdA9NpV
            JyKo23qFBTt6aCHA/51C4BUKHvg9qdJSvxMlLR0NK0fgc3SlWPIOnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:mf4bdxR606VglRGYaSYK1EdS14NsLLRq4ClFclU6KvdtmzsiRCwWpSPWuUnRpbohI582aT7948XugeKa2j7NHTqaZVRRL3amq2TJHvTekcGTPDq/MBhMJC9DVPHD5x87G9d0Of84bPtLExhz5JAorT4sceu+Wb677AZCpa57dCM=,iv:jVDfNbIuCmckNDXbQ7NdIsc7Jv+l3Q895+VVE3/FcMg=,tag:Q7VJHXcNmvf+UXpBxBS01Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
