apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:zK7icyGKCj3DZn+895qepBWHVBvEuIMonqJ3MjPPi3YMPxR0Qq36XbJm8V9NnJpQDHowKvF5yYB0UawJ,iv:kJXdfLpSRQKopE1pwpbD6b3GVRD152GlJN6+9slqg3k=,tag:lH2egzDDRXW4SeS/i4w5LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZnZiMHdRUDFuWWFIa3ZM
            RXBWZk9FTk1VUXM0WEhmQnRyd3JoMUFIOXprCkEvenl4SDEvNmNYcjU4eEFuc1lV
            ZkpQSGxtMHZ2KzBPN3RGWnRZZ0pkL00KLS0tIDgvSzczN096cHRmSVJMWUlNcEZj
            MWwvU0dKOUd4YUY0Q0NlSVQzd2ZmcUkKEIgO+8hBrnvptkH6gKisG8YqfD3f2NSk
            yOwIV/Os1EZ5KNsHDnJYtZTzKi+js4/gbxIMTCowdc0ueQu5nCRGlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:XhiweVrGvLKn2xq7QAaJOUOTnKU4i6LphT7OEy5QXXp2dq8AAw7Bwu8pRUTCN1FErn7/ktfmJr61EvFIng67vhiw9YQOOoZxUmEQkdb5AfmbNAHS1mjzW76hpIuA5LyegDXlxn+Wg/obTfMT009FtkfKtKV8uB1Q+oRemwAXox8=,iv:T4m35udELnVKwo8hz/ZnWiyimZfjfmNno46ojddCma8=,tag:lzPRTeRAfbiqBvkp3PjxKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
