apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:I4T+x0UsrxEDYTNPpOPOAQ/FyJ7npEDxCtCUgjSqkJc5+0ZDvyl6Azznjwzn88lOXUZrd03KG39UaPdX,iv:w2KqGdAG1VvLmTP8VpLIM2+BNyq0qC/Ns1uApRvC7B8=,tag:CUhbosFpsJX1Eq8esdDS/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRlRUV096ZFRwbG5yd2dV
            cmN2MUZSMXlBUTJwNkVWUUJJSGN6RTMxVGxrCnltRlN0MURjVDg4UXFyQTU1YUFr
            LzZid1A4WTJWbytEQnVOckNtbWorSm8KLS0tIFR2NkdRZjQ2anlCaWtPMnZqTUpu
            SkF0d3ViZGsyRHE1UFlCMUlHYWsxUjQKXR/1RMfcWT3ay2ExY8cjKod3ZvZCPbqO
            ReBm1jgvpAt6A69udexm37XtKqWdwqc+QyINNK7swV/7Y2w+b+SQ4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:hFAr9a+TMiXcZ+U/5gyh3hk/R9lkQ+pqca/dGQDVXrLqEbNnC/oT1/2V3kHiPXIQNJbyNQLqSft/ueaR3W4GYJ7WTEorvtsfteCnnvE4r3HnoTget6zZXlCn9Mr+84xZbCTzRRBxC2dP+srjKrAIhcRQGVE70kz6QGQVf6TULik=,iv:jVA0K527s6Rr4yN0VF7/OXU+Wjv7mFkQKL7LY27Q/Zc=,tag:qTqI+HeludrzBPTqTCESbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
