---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-hoperestored-pv
  namespace: kube-system
spec:
  storageClassName: config-hoperestored
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    # - nfsvers=3
    # - nolock
    # - tcp
    # - intr
    # - hard
    # - noatime
    # - nodiratime
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
  nfs:
    path: /mnt/std/kubepv
    server: hoperestored.h.sdboyer.io
