apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-hoperestored-pv
  namespace: media
spec:
  storageClassName: media-hoperestored
  capacity:
    storage: 20Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
  nfs:
    path: /mnt/std/media
    server: hoperestored.h.sdboyer.io
