---
# yaml-language-server: $schema=https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.6.9-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: default
spec:
  volumeName: iscsi-radarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
