---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Detroit"
  CLUSTER_CIDR: "10.42.0.0/16"
  NODE_CIDR: "10.10.1.0/24"

  PUBLIC_DOMAIN: boyers.club
  PUBLIC_EMAIL: sam@sdboyer.io

  NAS_HOSTNAME: hoperestored.h.sdboyer.io
  NAS_IP: "10.10.1.228"

  # Storage
  # CLUSTER_STORAGE_BLOCK: ceph-block
  CLUSTER_STORAGE_BLOCK: freenas-iscsi-csi
  # CLUSTER_SNAPSHOT_BLOCK: csi-ceph-block
  # CLUSTER_STORAGE_FILESYSTEM: ceph-filesystem
  # CLUSTER_SNAPSHOT_FILESYSTEM: csi-ceph-filesystem
  # CLUSTER_STORAGE_BUCKET: ceph-bucket
  # CLUSTER_STORAGE_HOSTPATH: democratic-csi-local-hostpath
  # CLUSTER_SNAPSHOT_HOSTPATH: csi-democratic-csi-local-hostpath
