apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CALs8Zu4Lx/urFk=,iv:SQw9zNMQqyLeOyNtOe0OY0MOzBrsGDwI593/IM5CSFc=,tag:go20hd0DagYP2HvcyQacCw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fWH8kU7iBexgBn9X1+U=,iv:EGVb+g/U/Z+I8+9QtNmF1872eyLoTEWpcRL9h0uNqyA=,tag:Cr2p2B+Q7Kl4E1BMc5Uefg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRlNLazZzeHF2REhYZXdL
            QXM4ZC9uYmxQcE5ISzJOOXR4Njh0NmpRRzJRCjVKNkZWRHBBRm1tTGNZUEg1Mkdw
            VDlMVTRsUS9sS0tkSHhWd2U5aFZXSk0KLS0tIFRBalpXVnZrUVlxRFgvQ2xGemEx
            K0NId2FuM3VGaEVOazdRNlA0MW9XbVEKI9k/w8+otaGjELU9zJsYtgGgSBEiU12B
            l7/B+gHp0uzJWLRPAdUQvz73kV0l6fjwwRuSzfhc+7cAoKoe1g3XUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T17:41:34Z"
    mac: ENC[AES256_GCM,data:S2HPzr4nbUI9EoPUrmyLrpu0Ys25Fhmy3CgGKsO4bNBd3hxil+ynoLPml8ROaiZhlPUdP8IEBCNqAqF0l98lOkwAjuHVKI86kWaH9e8GEVrivG3jOZIB+ZhC91icNI4Oai11y0W3n6CvFMdkKjMQjIbRt1l/Zsg6ChLG3nDJbxk=,iv:9dKXThuvSzENEPAs9x4qaUHZ6Bx7uu5GFrwcVK6sI0w=,tag:mWqFy7D0LRY9/K6ZKQCtKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
