apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mwdu4Uhkq7jb3w==,iv:v3kVQtV2sc1nzMx9INeq8JI8lWFAjOm8DTniYAAiiKs=,tag:cXuoe+9LCmNLvMSlBP4eQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:daXcpslZLwLkKTqvn0w=,iv:OYXZ1bYCiX9AADphYD4Kma0HiwZLZd+U1BiJ8arPe24=,tag:y/x8AysR05dvyQ2hjcz0NQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa672jh38snjn4rqv8kgknqlgcp26vxewau8pzvl2kfg7fyz2dnslvwcdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTk56NXVhMjQra1VKbkJn
            K1ZaTjBGdVpXU2ZtVmthamxtQ0tZc1IrZ0U4ClhtSjlOY0JZSjAydE1LaUJ6K1dy
            MVZKY3dQM3F5UmVrdEJmMkprUzE2N3MKLS0tIDRKeG9rV2VTcGx5dVA4Zy9OMXI0
            RVZ3bVhyZEFzNnFXUUYwWng5a3FEZjgKwfa0+qeYuLMLhy5mGmtoFFqYZFQVGiW2
            0T8YqhJYc6j9FIBjuJD2I71pJdCOcYLoONHCRGrHZv4E6F9vxizxHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T21:15:05Z"
    mac: ENC[AES256_GCM,data:SGbNpemhTjXJM3ONSVB/lSxz5TYOAA4V4namnFbdkdWHuIvQmOdvADzhKGAqLYd4BBwv0YRLzoVobdICgD11U9cFEQzYik6leK6tUn0QU2hMgQP2mjUssYOmtUJhF9HordaigGOFYRE1Jl4Mf3Ys4oQ3uEUgAyCJ5fvJbbYSUFE=,iv:z04q3zx2XMl52Gb8XLNbOjwKgw/WJmDl5YH813zDqE4=,tag:NLUH7TbSANcFoRvtuziEsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
