---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minecraft-server
  namespace: flux-system
spec:
  path: ./kubernetes/apps/minecraft/minecraft-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
  retryInterval: 1m
  timeout: 30s
