---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nzbget
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home/nzbget/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nzbget
      namespace: home
  interval: 15m
  retryInterval: 1m
  timeout: 30s
